/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <skinnedMesh geometry={nodes.SK_SOF_E.geometry} material={materials.MI_Shirt_ColorH} skeleton={nodes.SK_SOF_E.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_1.geometry} material={materials.MI_Pouches_ColorC} skeleton={nodes.SK_SOF_E_1.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_2.geometry} material={materials.MI_HeadGear_ColorI} skeleton={nodes.SK_SOF_E_2.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_3.geometry} material={materials.MI_Eye} skeleton={nodes.SK_SOF_E_3.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_4.geometry} material={materials.MI_EyeLashes} skeleton={nodes.SK_SOF_E_4.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_5.geometry} material={materials.MI_PatchesPOLIZEI_ColorC} skeleton={nodes.SK_SOF_E_5.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_6.geometry} material={materials.MI_Unloading_ColorC} skeleton={nodes.SK_SOF_E_6.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_7.geometry} material={materials.MI_Glass_A} skeleton={nodes.SK_SOF_E_7.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_8.geometry} material={materials.MI_Pants_ColorI} skeleton={nodes.SK_SOF_E_8.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_9.geometry} material={materials.MI_Unloading_ColorC} skeleton={nodes.SK_SOF_E_9.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_10.geometry} material={materials.MI_Pants_ColorH} skeleton={nodes.SK_SOF_E_10.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_11.geometry} material={materials.MI_Arms} skeleton={nodes.SK_SOF_E_11.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_12.geometry} material={materials.MI_Head} skeleton={nodes.SK_SOF_E_12.skeleton} />
      <skinnedMesh geometry={nodes.SK_SOF_E_13.geometry} material={materials.MI_Gloves_ColorD} skeleton={nodes.SK_SOF_E_13.skeleton} />
      <primitive object={nodes.root} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
